version: '3.8'

services:
  loadbalancer:
    image: nginx:1.13.6-alpine
    container_name: loadbalancer
    ports:
      - "8080:80"
    networks:
      - server
    volumes:
      - ./load-balancer.conf:/etc/nginx/nginx.conf

networks:
  server:
    name: server
