services:
  kotlinserver1:
    build: .
    container_name: kotlinserver1
    networks:
      - server
    volumes:
      - .:/code
    environment:
      - APP_NAME=kotlin_server_1
      - MICRONAUT_SERVER_HOST=0.0.0.0
      - MICRONAUT_SERVER_PORT=8000
    ports:
      - "8000:8000"

  kotlinserver2:
    build: .
    container_name: kotlinserver2
    networks:
      - server
    volumes:
      - .:/code
    environment:
      - APP_NAME=kotlin_server_2
      - MICRONAUT_SERVER_HOST=0.0.0.0
      - MICRONAUT_SERVER_PORT=8001
    ports:
      - "8001:8001"

  kotlinserver3:
    build: .
    container_name: kotlinserver3
    networks:
      - server
    volumes:
      - .:/code
    environment:
      - APP_NAME=kotlin_server_3
      - MICRONAUT_SERVER_HOST=0.0.0.0
      - MICRONAUT_SERVER_PORT=8002
    ports:
      - "8002:8002"

networks:
  server:
    name: server
